#copy index.html from host to server
- name: copy html for apache2
  copy: src=../templates/index.html dest=/var/www/html/index.html
  notify:
  - restart-apache
#copy info.php from host to server
- name: copy phpinfo for apache2
  copy: src=../templates/info.php dest=/var/www/html/info.php
  notify:
  - restart-apache
